package:
  name: surf
  version: {{ environ.get('GIT_DESCRIBE_TAG') }}

source:
   path: ..

build:
   number: {{ environ.get('GIT_DESCRIBE_NUMBER',0) }}

requirements:
   build:
     - python
     - rogue
     - git
     - gitpython
     - numpy
   host:
     - python
     - rogue
     - numpy
   run:
     - python
     - rogue
     - numpy

about:
   home: https://github.com/slaclab/surf
   license: SLAC Open License
   license_file: LICENSE.txt
   summary: SLAC Ultimate RTL Framework

